### ISSUE TITLE
Traceroute result presentation error

### ISSUE THREAD

**Issue by quietbamboo** [Mobiperf/MobiPerf#100]
One problem I found is about the traceroute measurement.

The result shown in the Results tab => Manual has some problems.

For the first hop:
"1 192.168.1. 37.3ms" it should be => "1 192.168.1.110 37.3ms"
Among the 15 hops in my case, 3 hops have this problem, that the last number of the IP address is missing.
But the other 12 hops are fine.
One suggestion I have is, to align the RTT numbers, e.g., 37.3ms in the example, to the right, while align the IP to the left.

**Comment by ghost** [comment]
Taking this one as it doesn't require too much depth of knowledge of the codebase.

**Comment by ghost** [comment]
Fixed in https://github.com/Mobiperf/MobiPerf/pull/103
