### ISSUE TITLE
Results temporarily disappear in the "Results" => "Manual" tab

### ISSUE THREAD

**Issue by quietbamboo** [Mobiperf/MobiPerf#101]
To reproduce this bug, first run any test so that in the "Manual" tab, there is some results to show.

Then go to "Results" => "Manual", there should be some results.

Then rotate the screen so that the app adjusts itself to the new orientation.

Then all results in the "Manual" tab is gone. But if you click "Scheduled" and then click "Manual" tab again, the results will reappear.

Instead, we should show the results immediately after the screen is rotated, otherwise, the user might get confused. This is a minor bug of course. I didn't check whether this bug also exists in the "Scheduled" tab, but it's quite possible.

**Comment by mdwelsh** [comment]
Right, this is a side effect of my fix to the race condition. We need some
safe way of polling for when the scheduler is available, or perhaps a new
intent. It's a little tricky so I've focused first on eliminating crashes
:-)

**Comment by ghost** [comment]
https://speedometer-reviews.appspot.com/29001/
