### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by quietbamboo** [Mobiperf/MobiPerf#102]
Bug found.

I've run MobiPerf this morning. I'm running it with Android 2.3.3, with WiFi access.

Attached is the debug.txt (output of adb logcat *:s 'Mobiperf') and bugreport.txt (output of adb bugreport).

What I've done is, first run an UDP down experiment (the result says PRR 0.0, so not sucessful?), then run an UDP up experiment (the results says experiment has failed, I'm not sure why). Then I go to results tab and also looked at the system logs. Then the app crashes.

I'm not exactly sure the cause of the crash, but I think it is NOT caused by this exception "java.lang.RuntimeException: No google account found" since I've observed the app working fine while producing it.

The file attachments are in the email. Search for "debug.txt" or "bugreport.txt" in your emails.

**Comment by mdwelsh** [comment]
Yeah, there's a known problem with switching between these views. It's been
hard to isolate... Is this crash consistently repeatable?

**Comment by quietbamboo** [comment]
It's not consistently repeatable. Hopefully, from my debug.txt and bugreport.txt, we can find some clue of what's happening during that crash.

**Comment by ghost** [comment]
Attachments at: https://gist.github.com/3776713

**Comment by ghost** [comment]
09-22 12:11:43.368   127   132 I am_crash: [1108,com.mobiperf.speedometer,572998,java.lang.IllegalStateException,The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. [in ListView(2131361792, class android.widget.ListView) with Adapter(class android.widget.ArrayAdapter)],ListView.java,1573]

Seems pertinent.

**Comment by mdwelsh** [comment]
Yes, this is the bug I've been trying to nail down. I'll keep working on it.

**Comment by ghost** [comment]
If this is the same as #85, we should probably close it.
