### ISSUE TITLE
Setting account doesn't store auth cookie

### ISSUE THREAD

**Issue by ghost** [Mobiperf/MobiPerf#107]
I noticed the scheduled tests were failing when anonymous so I set an account. This worked until i restarted, now i have no auth cookie again and tests are failing. Settings do show that an account is selected.

**Comment by drchoffnes** [comment]
I mentioned the bug related to logging in when anonymous -- should we consider it part of this same issue or should I start a new one?

**Comment by ghost** [comment]
@drchoffnes That should be covered under the existing 'testing anonymous' bug i think.

**Comment by ghost** [comment]
Seems to be working after my latest anonymization changes.
