### ISSUE TITLE
Menubar notification does not go away when app is quit

### ISSUE THREAD

**Issue by mdwelsh** [Mobiperf/MobiPerf#119]
The menubar notification should disappear when we quit the app.

To reproduce:
- Run Mobiperf
- Menubar icon should appear
- Go to settings > quit
- App seems to quit but menu bar icon still there - is the service still running?

**Comment by ghost** [comment]
My guess would be the background service is still running. If you quit the service from the manage apps screen in settings it should go away.

It's an Android thing: App 'quit' != kill all my services. We could make quit kill all services, but the OS has ways to do that already so I'm not sure it's actually needed. I suggest removing 'quit' from the menu.

**Comment by ghost** [comment]
Any thoughts on removing 'quit'? It really doesn't make sense to have it there as it doesn't kill the service.

**Comment by mdwelsh** [comment]
There needs to be a quick and easy way for a user to completely turn off
Mobiperf for whatever reason - battery drain, data usage, privacy concern,
etc. In the past, Quit actually did kill the service...

**Comment by ghost** [comment]
You don't think the app management setting in the OS is the place for this?

Users that care about this stuff will know about it and I'd guess they'd go
there first.

Of course, if its easy to kill the service then great, but I don't know
about that.

**Comment by mdwelsh** [comment]
Speedometer has supported this since the beginning so I know it's possible!

**Comment by ghost** [comment]
Fix ready for review at http://speedometer-reviews.appspot.com/38001/
