### ISSUE TITLE
Change server selection for scheduled tests

### ISSUE THREAD

**Issue by ghost** [Mobiperf/MobiPerf#126]
Google domains
m-lab servers
UMich servers
UW servers

**Comment by drchoffnes** [comment]
This is (finally) done. Now probing some Google, Mlab and Youtube sites.

**Comment by ghost** [comment]
i haven't seen a pull request or any commits. should i expect one?

**Comment by drchoffnes** [comment]
Nope, this is managed entirely via the Web interface at
http://openmobiledata.appspot.com/.

**Comment by ghost** [comment]
Oh, neat!

**Comment by mdwelsh** [comment]
Awesome! Are there any static images on the mlab servers you can point HTTP
GET tasks to? This is really useful for getting bandwidth estimates.
Measuring www.google.com doesn't tell you a whole lot :-)

**Comment by drchoffnes** [comment]
I couldn't find an image (all the visualizations are dynamic content!), so
I added a URL for a ~100K PDF.

**Comment by mdwelsh** [comment]
Oh, I meant an image hosted on the M-Lab servers themselves (not on the
main mlab website).

You can also measure

http://www.google.com/help/hc/images/mapmaker_188657_light_en.jpg

which is a fairly large static image.

**Comment by drchoffnes** [comment]
I'm a little worried about having clients regularly download a 2M image in
the background. Maybe just once a day?

**Comment by mdwelsh** [comment]
Yeah, good idea, especially until we get data usage limits in place. If you
can find a smaller static image hosted on a Google domain that works too...
