### ISSUE TITLE
Settings to select account again/ sign out

### ISSUE THREAD

**Issue by quietbamboo** [Mobiperf/MobiPerf#14]
Add settings to allow the user to change their authentication account anytime (not just the first time they run the app) and allow them to sign out.

Whether to allow them to sign out is to be discussed.
If we do, do we allow anonymous experiments?
If not, we can't allow them to sign out.

**Comment by mdwelsh** [comment]
Waiting for server-side support for anonymous data upload.

**Comment by quietbamboo** [comment]
Looks like this is already done http://speedometer-reviews.appspot.com/11001/
