### ISSUE TITLE
AppEngine support for anonymous data collection

### ISSUE THREAD

**Issue by drchoffnes** [Mobiperf/MobiPerf#16]
Allow data to be collected even if user is not logged in.

**Comment by mdwelsh** [comment]
Ping. Has this been done?

**Comment by drchoffnes** [comment]
Nope, not yet. I will get to that once I sort out the previous pull
request reviews.

On Sat, May 19, 2012 at 4:18 PM, Matt Welsh
reply@reply.github.com
wrote:

**Comment by drchoffnes** [comment]
My initial implementation is running at
http://anonymization-test.openmobiledata.appspot.com/. Junxian and
Shuheng will modify the app to confirm it works beyond the test data I
sent via python scripts.

**Comment by mdwelsh** [comment]
Ping? What's the status of this?

**Comment by drchoffnes** [comment]
The code supporting this is still at
http://anonymization-test.openmobiledata.appspot.com/. I've been waiting
for confirmation from Junxian/Shuheng that this works before submitting a
code review.

@Junxian/Shuheng: Can you please let me know when you've tested this?

**Comment by huangshu91** [comment]
In the previous version this was added already but the feature was rolled
back.  During the last meeting Matt mentioned that this was on the todo but
I think it's up to Dominic now.

**Comment by ghost** [comment]
It is something that we want for the beta release, so we should roll this back in.

mdwelsh: was there an issue with how this was implemented?

**Comment by mdwelsh** [comment]
No, I think the implementation done by the UMich guys could be cherrypicked
into the new code. The issue here is that we reverted to the Speedometer
code for the Android app, given all the lingering problems with the
previous code.

**Comment by ghost** [comment]
The Client code is in. Please close this when it's been tested.

**Comment by ghost** [comment]
I closed the other issue relating to this and assigned this to drchoffnes for testing.

**Comment by drchoffnes** [comment]
Can we send out builds that implement the features that need to be tested
on GAE? I don't see the option for account switching in the latest version
that was sent out. I'll try building from source for now, but it's easier
to get non-developers to test for us if we have an APK to distribute.

**Comment by ghost** [comment]
sent by email to the list.

**Comment by drchoffnes** [comment]
For whatever reason, the app is still trying to login when set to
anonymous. This is unnecessary and causes the app to fail to proceed. It
should skip any attempt to authenticate before contacting GAE when set to
anonymous reporting. Here's the offending GET:

GET /anonymous/_ah/login?continue=
https://anonymous-reporting-test.openmobiledata.appspot.com/anonymous&action=Login&auth=DQAAAMQAAAAFeGVbpQjplv7swy-_GlqGB9drqtl0ma_6gMJ_4xaz6HojkEqgPahB1e8dYcWH_i0gWj22Zl349VbnR0KnpPFi72GJYwIwlZsF4PlcOUJgdR8TRHJ02qgJScu8-ltnNbez4Swzevxggd4nlmwamxhKJ6w6cy_4WFpfkrXHEwjhU3DVUy6d9TbDJDk4JhuC_HEgPQeAEgMuiugIUmMCzHoBTXAiJy7ftpBREsSJFE96SsjanE9gmqK-OSgadPxtQFoHHJw9RTZX_SHs3PZm8vmA

**Comment by ghost** [comment]
@huangshu91 Can you take a look at this?

It seems that it's correctly skipping trying to authenticate when the user is set to anonymous, but it's then failing the checkin as an authCookie is expected. I don't know if the best thing to do is use a fake auth cookie for anonymous, or change the checkin code to check the active account. Your call.

Stack trace:

Got exception during checkin
E/Mobiperf(  566): java.io.IOException: No authCookie yet
E/Mobiperf(  566):  at com.mobiperf.speedometer.Checkin.speedometerServiceRequest(Checkin.java:320)
E/Mobiperf(  566):  at com.mobiperf.speedometer.Checkin.checkin(Checkin.java:154)
E/Mobiperf(  566):  at com.mobiperf.speedometer.MeasurementScheduler.getTasksFromServer(MeasurementScheduler.java:641)
E/Mobiperf(  566):  at com.mobiperf.speedometer.MeasurementScheduler.access$1200(MeasurementScheduler.java:71)
E/Mobiperf(  566):  at com.mobiperf.speedometer.MeasurementScheduler$CheckinTask.run(MeasurementScheduler.java:739)
E/Mobiperf(  566):  at java.lang.Thread.run(Thread.java:1019)

**Comment by huangshu91** [comment]
I am discussing with Junxian how to proceed because this semester I am very
busy.  We will take care of this but it might be a different student.

**Comment by ghost** [comment]
OK, that's fine. I only asked you as you're most familiar with the code.
Please do bear in mind the goal of getting this fixed asap so we can launch
in the next month or so.

**Comment by mdwelsh** [comment]
So, I think the deal is that the AppEngine server needs to be configured to not require authentication in order for the Android app to talk to it. I believe there's an option in the AppEngine YAML file to disable the need for authentication. You can also test this by visiting the website which should let you browse around without having logged in.

**Comment by ghost** [comment]
That's been done as I understand it, at least on the version that is not
live, but the app itself has broken logic: One part is skipping the
creation of the auth cookie, and the part that runs the scheduled tasks is
still expecting an auth cookie. It should be as simple as changing the
latter to not require an auth cookie if the selected account is the
anonymous one, but I am not confident enough with this part of the code to
be sure.

**Comment by ghost** [comment]
@drchoffnes I have now made a local change that enables checkin to the anonymization-test instance and I get a bad response: https://gist.github.com/3789261

It looks suspiciously like a request to choose an account...

**Comment by drchoffnes** [comment]
When the account is set to anonymous, all code for checking in and
posting measurements should use

/anonymous/[page]

instead of just

/[page]

I think this is the source of the problem you posted.

**Comment by ghost** [comment]
Got it - and the code is out for review that should fix this.

My local test checked in ok but i can't seem to find anonymous data on the
site to verify that the checkin worked.

**Comment by ghost** [comment]
Checked in the version that correctly checks in when anonymous. @drchoffnes when you can, please confirm that the anonymous checkins are showing up on GAE (and where to see those anonymous checkins).

**Comment by huangshu91** [comment]
Thanks for finishing this.  Sorry that we were not able to provide anyone
in time.

**Comment by drchoffnes** [comment]
I see one anonymous checkin+data from Brussels and a bunch from UMich. So
it looks like it's working. Could you send out the APK again at some point?
Or can we move to some kind of "nightly build" system? I'd like to do more
testing.

Sorry for being so unresponsive. Should be better over the next week.

**Comment by ghost** [comment]
No problem  - In that case can you make the anonymous-reporting-test the default and i'll change the anonymous server to point to the normal url?

good idea re nightly build. we don't have infrastructure for that but could just send out builds every day there's a fix. i'll work on a new build now.

**Comment by drchoffnes** [comment]
Anonymous reporting is also the default already :-)

**Comment by ghost** [comment]
updated the client to match. done!
