### ISSUE TITLE
Boot Receiver bug

### ISSUE THREAD

**Issue by drchoffnes** [Mobiperf/MobiPerf#18]
The manifest file has the wrong package name specified for the boot receiver:

com.mobiperf.mobiperf.WatchdogBootReceiver

should be 

com.speedometer.speed.WatchdogBootReceiver

... or you can move the class to the package specified in the manifest. 

H/t to Seungyeop for finding the root cause.

**Comment by quietbamboo** [comment]
Thanks. I've fixed it in my branch.
Will make a pull request once Matt has merged my last pull request.

**Comment by drchoffnes** [comment]
Awesome, thanks! It might be a good idea to e-mail an updated apk to
the mobiperf list -- I had to turn off my phone for a flight this
weekend and didn't realize Mobiperf didn't come back on until I got
back today. :-(

On Tue, Apr 10, 2012 at 12:40 PM, Junxian Huang
reply@reply.github.com
wrote:

**Comment by quietbamboo** [comment]
I've just sent out a new APK to our google group.

**Comment by mdwelsh** [comment]
Where is this fix?
