### ISSUE TITLE
README is lacking

### ISSUE THREAD

**Issue by gavaletz** [Mobiperf/MobiPerf#21]
I had no idea that there was documentation.  My understanding is that functionally very little has changed from the speedometer code.  With that in mind can we update the MobiPerf README with the stuff from here (with changes as needed of course).

https://github.com/Mobiperf/MobiPerf/blob/master/README

**Comment by quietbamboo** [comment]
Good suggestion. I will add this once my currently pending pull request get resolved.

**Comment by mdwelsh** [comment]
This has been done.
