### ISSUE TITLE
gpsEnabled is set to false by default.

### ISSUE THREAD

**Issue by haneul** [Mobiperf/MobiPerf#41]
It should be true.
Also, even after setting through preferences it's reset after rebooting (or process killed and rerun) as the value is not loaded from preferences.

**Comment by quietbamboo** [comment]
This is already fixed, please close this issue after merging the current pull request

**Comment by haneul** [comment]
I checked the pull request, but I assume that it requires to change MeasurementScheduler::gpsEnabled value rather than changing only Preference?

**Comment by huangshu91** [comment]
You are right.  I added a few lines to check for starting value in the next commit.

**Comment by haneul** [comment]
@huangshu91  Do you mean the commits are also in the pull request?

**Comment by huangshu91** [comment]
No, I just mean that I took another look, made some changes, and committed for Junxian to review.  I have MeasurementScheduler check the preferences for the default setting upon creation.  I think this should be enough to fix the problem.

**Comment by huangshu91** [comment]
Should be done.
