### ISSUE TITLE
Feature: App needs to display version information

### ISSUE THREAD

**Issue by mdwelsh** [Mobiperf/MobiPerf#49]
version info needs to be on the splash page and on the "About Us" page.

**Comment by quietbamboo** [comment]
So what's the version number to put into the splash page? v1.0?

**Comment by quietbamboo** [comment]
I added v 1.0 to about and splash screen.
I've submitted a review request.

**Comment by mdwelsh** [comment]
I didn't see a review request - be sure you mail it to me from the
review system.

On Thu, May 31, 2012 at 12:49 PM, Junxian Huang
reply@reply.github.com
wrote:

**Comment by quietbamboo** [comment]
I just did. When I submit, upload.py throws some error saying that my image file is too large to be uploaded (about 600KB). But it's fine, I just added a version number to the right bottom of the splash screen image.

**Comment by quietbamboo** [comment]
Done with pull request https://github.com/Mobiperf/MobiPerf/pull/56
