### ISSUE TITLE
Make MobiPerf automatically starts when reboot

### ISSUE THREAD

**Issue by quietbamboo** [Mobiperf/MobiPerf#65]
Check whether MobiPerf automatically starts when reboot, if not, implement it

**Comment by mdwelsh** [comment]
Code review out for this now.

**Comment by mdwelsh** [comment]
Ping?

**Comment by quietbamboo** [comment]
I believe Shuheng has finished this part.
I will wait for Shuheng's feedback on this

**Comment by mdwelsh** [comment]
Not done yet, but in progress: http://speedometer-reviews.appspot.com/6002/
