### ISSUE TITLE
Version numbering needs to be cleaned up

### ISSUE THREAD

**Issue by mdwelsh** [Mobiperf/MobiPerf#68]
Version numbers are a mess. The app splash screen and "About" page say 1.0. The Android Settings > Apps page for Mobiperf says 0.2. There needs to be a consistent version numbering scheme and this needs to be very clear to the user.

**Comment by quietbamboo** [comment]
The plan is to have the consistent version number in the splash screen and about by reading from the app package. The app version goes from 0.2 to 0.3 0.4 until 1.0 for the initial release.

In the splash screen, a text box will be added at the right bottom corner for showing the version text.

**Comment by mdwelsh** [comment]
Ping?

**Comment by quietbamboo** [comment]
I believe this is solved here https://github.com/Mobiperf/MobiPerf/pull/73
Shuheng will merge the pull request later.

**Comment by quietbamboo** [comment]
Closing the issue now since the only left thing is the pending pull request, we can reopen it if anyone disagrees with the closing
