### ISSUE TITLE
Android support for anonymous data collection

### ISSUE THREAD

**Issue by mdwelsh** [Mobiperf/MobiPerf#87]
We had this in the previous Mobiperf codebase (before reverting back to Speedometer) and it was addressed in this pull request:

https://github.com/Mobiperf/MobiPerf/pull/74

We should make the same change in the newest version of the code.

**Comment by ghost** [comment]
It isn't quite as easy as cherry-picking those commits as we also have to add a preferences activity.

Should we start with anonymous as the default?

**Comment by huangshu91** [comment]
If I remember correctly what happened was after consenting, the next dialog
would show a list of accounts as well as anonymous with anonymous as the
preselected choice.  Afterwards, in the preferences there was an option to
pop up this dialog again and reselect account.
